### ISSUE TITLE
Settings help

### ISSUE THREAD

**Issue by stargirls** [Labs64/credit-tracker#16]
Hi
I am not very technical so I am having some issues understanding exactly how this works ( the FAQs) are not that clear for me.
I added a URL to the 'link' section in the image uploader but it doesn't show.Can you advise?

Thanks

**Comment by kkorotkov** [comment]
Dear sender,

Thank you for your email. I'm not available until August 16th, and will respond upon my return.

Best Regards,
Konstantin Korotkov

**Comment by r-brown** [comment]
Hello,

please check this *Step-by-Step instruction :: How to add custom image caption*: https://github.com/Labs64/credit-tracker/issues/10#issuecomment-100102644

Best Regards,
  R.Brown

**Comment by stargirls** [comment]
Hello
With the latest version of WP, there is no image attachment id in the
permalink. Does this mean the plugin can't work with most up to date WP?
Thanks

**Comment by stargirls** [comment]
Hi
Ignore last email, I got it working. Only issue is that the credit line is
not under the image like in your example.How do I do that please?
Thanks

**Comment by r-brown** [comment]
Hi @stargirls, could you please share your test page of HTML snippet around rendered image?
