### ISSUE TITLE
Request for new stock agency

### ISSUE THREAD

**Issue by WPExpert** [Labs64/credit-tracker#21]
Retrieve Media information from an additional stock agency ~ UnSplash [https://unsplash.com/]

**Comment by r-brown** [comment]
Hi @WPExpert this is for sure great idea. We are also using [unsplash.com](https://unsplash.com) as media source for our [blog](http://netlicensing.io/blog/).

**Comment by r-brown** [comment]
Wit the new Credit Tracker version [1.1.8](https://wordpress.org/plugins/credit-tracker/changelog/) we've introduced a new stock agency - [Unsplash](https://unsplash.com/)

**Comment by WPExpert** [comment]
Super cool!
