### ISSUE TITLE
ro_RO translation files :)

### ISSUE THREAD

**Issue by DeliciousThemes** [Labs64/credit-tracker#32]
Hey guys,

I want to say that this is a great plugin and I've been using it with success for a project of my own.

To return the favor, here are the romanian translation files I created. 

[credit-tracker-ro_RO.zip](https://github.com/Labs64/credit-tracker/files/1523997/credit-tracker-ro_RO.zip)

Thanks!

**Comment by r-brown** [comment]
Hi @DeliciousThemes,
Thank you for your feedback and translation submission.
