### ISSUE TITLE
Credit Tracker shortcode, display images by tag?

### ISSUE THREAD

**Issue by r-brown** [Labs64/credit-tracker#34]
I am using Credit Tracker – love the plugin! – to track the CC licensing for images that we are using on our pages.

Here is an example – https://tellibrary.org/lessons/understanding-mass-communication/
at the bottom under License and Citations.

I am also using a plugin called Enhanced Media Library which allows me to use the word press taxonomy (Categories and Tags) in the Media Library – so every image has a Categories and Tags.

Would it be possible to pull the citations that I need through the shortcode by Tag instead of having to list each library item number?

----

Source: https://wordpress.org/support/topic/credit-tracker-shortcode-display-images-by-tag/

**Comment by Jaace** [comment]
I could take a look into this if no one else has taken already.

**Comment by r-brown** [comment]
Hello @Jaace , sure - feel free. Thanks!

**Comment by dmchale** [comment]
If #51 is approved, it would be possible to use a WordPress filter to update the behavior as requested in this Issue. The 'Enhanced Media Library' plugin uses a custom taxonomy to categorize the Media Library, so a tax_query would be required to get the images that you want. 

The following code could be added to the `functions.php` file of your theme. 

`function my_credittracker_filter( $args ) {

    if ( 12345 == get_queried_object_id() ) {   // Replace 12345 with the postID of the page you wish to run this on, or remove this line and the closing } below to remove
	    $args['tax_query'] = array(
		    array(
			    'taxonomy' => 'media_category',
			    'field'    => 'slug',
			    'terms'    => array( 'my test category' ),   // enter the name(s) of your categories here in the array
			    'operator' => 'IN',
		    )
	    );
    }

    return $args;
}
add_filter( 'credittracker_get_images_args', 'my_credittracker_filter', 10, 1 );`
